name: simon_says_hope
description: A new Flutter project.

version: 1.0.3+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  confetti: ^0.6.0
  cupertino_icons: ^1.0.0
  day_night_switcher: ^0.2.0+1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.5.2
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.2.0
  firebase_storage: ^10.1.0
  freezed_annotation:
  get: ^4.6.1
  get_storage:
  getwidget: ^2.0.4
  http: ^0.13.1
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  material_design_icons_flutter: ^5.0.6295
  new_version: ^0.3.0
  package_info_plus: ^1.4.0
  platform_device_id: ^1.0.1
  table_calendar: ^3.0.5
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^0.15.1+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
